### ISSUE TITLE
Host platform must have ruby installed

### ISSUE THREAD

**Issue by jmjatlanta** [bitshares/bitshares-gitian#20]
I created a new VM for Ubuntu 16.04, but failed on the ./run-gitian script, as `gbuild` said "file not found". It turns out that gbuild requires ruby, which was not installed on the VM. So, perhaps include this in the README.md?

**Comment by pmconrad** [comment]
Actually our README points to the origin [gitian README](https://github.com/devrandom/gitian-builder/blob/master/README.md) wrt preparing the environment. That in turn is not very explicit about ruby, it's only mentioned in some places but e. g. not for Docker on Ubuntu.
IMO this should be fixed upstream.
