### ISSUE TITLE
Add BitShares to reproducible-builds.org

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares-gitian#21]
The reproducible-builds.org site provides listings of projects supporting gitian builds, including bitcon and Monero. Once we get this build process fully sorted, we can request inclusion. Seems that may require an annual donation of at least $5000 https://reproducible-builds.org/sponsor/

**Comment by pmconrad** [comment]
As I see it [here](https://reproducible-builds.org/who/), the "Projects" section is listed not below "Sponsors" but on the same level with it (hierarchy-wise). I'd guess that a "Project" listing would not require a monetary contribution. Need to ask them anyway though.

**Comment by pmconrad** [comment]
Logo for listing: https://bitshares.org/assets/images/logo.png

**Comment by pmconrad** [comment]
Added PR on their website repo - https://salsa.debian.org/reproducible-builds/reproducible-website/merge_requests/46

**Comment by pmconrad** [comment]
Yay! https://reproducible-builds.org/who/
